### ISSUE TITLE
pandas StringMethod.partition does not exist in older pandas (0.13.x)

### ISSUE THREAD

**Issue by ctb** [camillescott/dammit#15]
If the use of str.partition(...) is removed from parsers.py:crb_to_df_iter(), then we can get by with the version of pandas that will install with apt-get on Ubuntu 14.04. Otherwise we need to specify pandas 0.17 or above, I think.

**Comment by camillescott** [comment]
Hmm. 0.13 is really old... looks like str.partition(...) was introduced in 0.16.1. I'll give it some more thought, but for now I think i'll just enforce >= 0.16.1.

**Comment by ctb** [comment]
On Sun, Nov 08, 2015 at 08:21:15PM -0800, Camille Scott wrote:
> Hmm. 0.13 is really old... looks like str.partition(...) was introduced in 0.16.1. I'll give it some more thought, but for now I think i'll just enforce >= 0.16.1. 

OK. Note,

* this is a 5 minute difference in installation on the most recent Ubuntu
  LTS (apt-get install vs compiling);

* pandas 0.13 is less than two years old;

* I think this is the only remaining version incompatibility left in the code
  base, and it's only two lines of code that could be easily replaced by
  someone who groks pandas.

So I think it is reasonably user-focused to support the LTS since it's
such a small hack.

**Comment by camillescott** [comment]
On Mon, Nov 9, 2015 at 6:23 AM, C. Titus Brown <notifications@github.com>
wrote:

> On Sun, Nov 08, 2015 at 08:21:15PM -0800, Camille Scott wrote:
> > Hmm. 0.13 is really old... looks like str.partition(...) was introduced
> in 0.16.1. I'll give it some more thought, but for now I think i'll just
> enforce >= 0.16.1.
>
> OK. Note,
>
> * this is a 5 minute difference in installation on the most recent Ubuntu
> LTS (apt-get install vs compiling);
>

Good point. This is why I recommend people use anaconda/miniconda, but not
everyone wants to go that route.


>
> * pandas 0.13 is less than two years old;
>

Yeah, but the project has come a very long way since then -- many bugs have
been fixed, speed improvements made, and functionality introduced, which is
relevant because --


>
> * I think this is the only remaining version incompatibility left in the
> code
> base, and it's only two lines of code that could be easily replaced by
> someone who groks pandas.
>

-- I now have code to do all the CRBB stuff in python with scikit learn and
LAST (or really any aligner), which is ridiculously faster and makes
databases like OrthoDB or even uniref much more reasonable to use. The code
introduces as a lot more reliance on pandas, and I'm not sure what effect
rolling back to 0.13 will have on it. However, because of this:


>
> So I think it is reasonably user-focused to support the LTS since it's
> such a small hack.
>

i'm willing to test it out and see :) So, I'll leave this open and come
back to it in a few days.


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/camillescott/dammit/issues/15#issuecomment-155077268>.
>



-- 
Camille Scott

Department of Computer Science
Lab for Data Intensive Biology
University of California, Davis

camille.scott.w@gmail.com

**Comment by ctb** [comment]
+1 thx

**Comment by camillescott** [comment]
verdict: 0.13 is ancient, use a newer version.
