### ISSUE TITLE
dammit docs don't seem to be built properly

### ISSUE THREAD

**Issue by ctb** [camillescott/dammit#54]
See 'details' under https://dammit.readthedocs.org/en/latest/

**Comment by camillescott** [comment]
Ah! This is because readthedocs isn't up to date; I had given up on it in favor of my own hosting because it couldn't do Cython builds. The actually docs are camillescott.org/dammit. I should get rid of the readthedocs site (or update it, now that i've gotten rid of the cython dep). Thanks for the reminder!

**Comment by camillescott** [comment]
Of course, it looks like that link is broken too, so I'll fix it both places ;)

**Comment by camillescott** [comment]
readthedocs build is now fixed. Made a couple of changes to the docs while I was at it. The issue you point to turns out not to be an issue though -- that's just Sphinx's autogenerated page index, and it seems like it's broken because the page is too short to do any scrolling.
